/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSlotRouteImport } from './routes/_authenticated/slot'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedLobbyRouteImport } from './routes/_authenticated/lobby'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedCrashRouteImport } from './routes/_authenticated/crash'
import { Route as AuthenticatedBlackjackRouteImport } from './routes/_authenticated/blackjack'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlotRoute = AuthenticatedSlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLobbyRoute = AuthenticatedLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrashRoute = AuthenticatedCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlackjackRoute = AuthenticatedBlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/blackjack': typeof AuthenticatedBlackjackRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/slot': typeof AuthenticatedSlotRoute
  '/store': typeof AuthenticatedStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/blackjack': typeof AuthenticatedBlackjackRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lobby': typeof AuthenticatedLobbyRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/slot': typeof AuthenticatedSlotRoute
  '/store': typeof AuthenticatedStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/blackjack': typeof AuthenticatedBlackjackRoute
  '/_authenticated/crash': typeof AuthenticatedCrashRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/lobby': typeof AuthenticatedLobbyRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/slot': typeof AuthenticatedSlotRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/blackjack'
    | '/crash'
    | '/leaderboard'
    | '/lobby'
    | '/plans'
    | '/profile'
    | '/slot'
    | '/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/blackjack'
    | '/crash'
    | '/leaderboard'
    | '/lobby'
    | '/plans'
    | '/profile'
    | '/slot'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/blackjack'
    | '/_authenticated/crash'
    | '/_authenticated/leaderboard'
    | '/_authenticated/lobby'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/slot'
    | '/_authenticated/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slot': {
      id: '/_authenticated/slot'
      path: '/slot'
      fullPath: '/slot'
      preLoaderRoute: typeof AuthenticatedSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lobby': {
      id: '/_authenticated/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof AuthenticatedLobbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crash': {
      id: '/_authenticated/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof AuthenticatedCrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blackjack': {
      id: '/_authenticated/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof AuthenticatedBlackjackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlackjackRoute: typeof AuthenticatedBlackjackRoute
  AuthenticatedCrashRoute: typeof AuthenticatedCrashRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLobbyRoute: typeof AuthenticatedLobbyRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSlotRoute: typeof AuthenticatedSlotRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlackjackRoute: AuthenticatedBlackjackRoute,
  AuthenticatedCrashRoute: AuthenticatedCrashRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLobbyRoute: AuthenticatedLobbyRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSlotRoute: AuthenticatedSlotRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
